#! /bin/sh  
#shell script takes care of starting and stopping  
# the glassfish DAS and glassfish instance.  
#  
# chkconfig: - 64 36  
# description: Tomcat auto start  
# /etc/init.d/tomcatd  
# Tomcat auto-start  
# Source function library.  
#. /etc/init.d/functions  
# source networking configuration.  
#. /etc/sysconfig/network  
. /root/.bashrc
RETVAL=0
export CATALINA_HOME=/app/tomcat/apache-tomcat-7.0.73
start()  
{  
        if [ -f $CATALINA_HOME/bin/startup.sh ];  
          then  
            echo $"Starting Tomcat"  
                $CATALINA_HOME/bin/startup.sh  
            RETVAL=$?  
            echo "OK"  
            return $RETVAL  
        fi  
}  
stop()  
{  
        if [ -f $CATALINA_HOME/bin/shutdown.sh ];  
          then  
            echo $"Stopping Tomcat"  
                $CATALINA_HOME/bin/shutdown.sh
            while [ -f /app/tomcat/apache-tomcat-7.0.73/run/tomcat.pid ]
            do
		echo "waitting..."
		sleep 2
            done  
            RETVAL=$?  
            sleep 1
            #ps -ef | grep apache-tomcat | grep -v 'grep' | awk '{print $2}' | xargs kill -9            
            echo "OK"  
            # [ $RETVAL -eq 0 ] && rm -f /var/lock/...  
            return $RETVAL  
        fi  
}  
  
case "$1" in  
 start)   
        start  
        ;;  
 stop)    
        stop  
        ;;  
                                                  
 restart)  
         echo $"Restaring Tomcat"  
         $0 stop  
         sleep 1  
         $0 start  
         ;;  
 *)  
        echo $"Usage: $0 {start|stop|restart}"  
        exit 1  
        ;;  
esac  
exit $RETVAL 
